# Generated by Django 5.0.6 on 2024-05-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_meterial_testuser_testuserquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testuser',
            table='test_user',
        ),
        migrations.AlterModelTable(
            name='testuserquestion',
            table='test_user_answer',
        ),
        migrations.AlterModelTable(
            name='testuserquestionanswer',
            table='test_user_answer_question',
        ),
    ]
