# Generated by Django 5.0.6 on 2024-05-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_result_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meterial',
            new_name='Material',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответы к вопросам', 'verbose_name_plural': 'Ответы к вопросам'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос к тесту', 'verbose_name_plural': 'Вопросы к тестам'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результат тестирования', 'verbose_name_plural': 'Результаты тестирования'},
        ),
    ]
