# Generated by Django 5.0.6 on 2025-01-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_question_title_alter_test_title'),
        ('tests', '0012_result_compleated_at'),
    ]

    operations = [
    ]
