services:
  web:
    container_name: irm-server
    build: ./irm_backend
    command: gunicorn irm_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./irm_backend/static:/home/project/static
      - ./irm_backend/db.sqlite3:/home/project/db.sqlite3
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - ./irm_backend/static:/home/project/static
    ports:
      - 8100:80
    depends_on:
      - web