services:
  web:
    build: ./irm_backend
    command: gunicorn irm_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/project/static
      - ./irm_backend/db.sqlite3:/home/project/db.sqlite3
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - ./irm_backend/static:/home/project/static
    ports:
      - 8100:80
    depends_on:
      - web

volumes:
  static_volume: