services:
  web:
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_HOST: db
    container_name: irm-server
    build: ./irm_backend
    command: gunicorn irm_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./irm_backend/static:/home/project/static
    expose:
      - 8000
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    volumes:
      - ./irm_backend/static:/home/project/static
    ports:
      - 8100:80
    depends_on:
      - web

volumes:
  postgres_data: