# Generated by Django 5.0.6 on 2024-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='text',
            field=models.TextField(verbose_name='Материал'),
        ),
    ]
