# Generated by Django 5.0.6 on 2024-06-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_title_alter_material_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='', verbose_name='uploads/')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atachments', to='materials.material')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_type', to='materials.filetype')),
            ],
        ),
    ]
