# Generated by Django 5.0.6 on 2024-06-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_filetype_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='filetype',
            options={'verbose_name': 'Тип файла', 'verbose_name_plural': 'Тип файлов'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='file', max_length=255, verbose_name='Имя файла'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_type', to='materials.filetype', verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atachments', to='materials.material', verbose_name='К какому материалу'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
