# Generated by Django 5.0.6 on 2024-07-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_attachment_options_alter_filetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='materials.material', verbose_name='К какому материалу'),
        ),
    ]
