# Generated by Django 5.0.6 on 2024-07-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Прикрипление', 'verbose_name_plural': 'Прикрепления'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=models.FileField(upload_to='static/uploads/', verbose_name='Файл'),
        ),
    ]
