# Generated by Django 5.0.6 on 2024-07-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_attachment_options_alter_attachment_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='material',
        ),
        migrations.AddField(
            model_name='attachment',
            name='theme',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='materials.theme', verbose_name='К какому материалу'),
            preserve_default=False,
        ),
    ]
