# Generated by Django 5.0.6 on 2024-07-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_remove_attachment_material_attachment_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmenttype',
            old_name='title',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='materials.theme', verbose_name='К какому материалу'),
        ),
    ]
