# Generated by Django 5.0.6 on 2024-09-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_rename_title_attachmenttype_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя раздела')),
                ('url', models.URLField(null=True, verbose_name='Ссылка на раздел')),
            ],
            options={
                'verbose_name': 'Раздел сайта',
                'verbose_name_plural': 'Разделы сайта',
            },
        ),
    ]
