# Generated by Django 5.0.6 on 2024-09-19 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='materials.section', verbose_name='К какому разделу сайта'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='materials.theme', verbose_name='К какому материалу'),
        ),
    ]
