# Generated by Django 5.0.6 on 2024-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_department_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='fio',
            field=models.TextField(default=1, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
