# Generated by Django 5.0.6 on 2024-09-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_alter_employee_options_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Отдел', to='materials.department', verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
