# Generated by Django 5.0.6 on 2024-12-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка на раздел'),
        ),
    ]
