# Generated by Django 5.0.6 on 2024-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_alter_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=models.FileField(max_length=4096, upload_to='static/uploads/', verbose_name='Файл'),
        ),
    ]
